### PR TITLE
Allow middlewares to be used for options requests

### PR DESCRIPTION
**Pull request by alexghr**
This PR allows custom middleware functions to be defined for options requests. It should fix this issue https://github.com/koajs/trie-router/issues/40

### CODE REVIEW

**Comment by alexghr** [comment]
Oups I'll fix the test 😅

**Comment by nervgh** [comment]
Thank you very much for your contribution! :+1: 

> I would have liked to move the logic at lines 165-167 into the preBottom function but that would have required a major version bump since the stack of middleware would no longer run on a ctx with the Allows header and HTTP 204 status.

What do you think about this?

```js
  /**
   * @param {Object} ctx
   * @param {Function} next
   * @return {Promise}
   */
  [__MIDDLEWARE](ctx, next) {
    let match
    try {
      match = this.trie.match(ctx.request.path)
    } catch (err) {
      err.code = 'MALFORMEDURL'
      throw err
    }

    let isMatched = isObject(match)
    let node = isMatched ? match.node : NODE_GAG
    node.methods = node.methods || NODE_GAG.methods
    ctx.params = ctx.request.params = isMatched ? match.param : {}

    let top = getMiddleware(this.methods, 'ANY') // router.use(fn)
    let middle = getMiddleware(this.methods, ctx.method) // router[method](fn)
    let bottom = getMiddleware(node.methods, ctx.method) // router[method](path, fn)

    let stack = [
      ...top,
      preMiddle.bind(this),
      ...middle,
      preBottom.bind(this),
      ...bottom
    ]

    let fn = compose(stack)
    return fn(ctx, noop)

    // ----------------

    function preMiddle (ctx, goToMiddleMiddleware) {
      // OPTIONS support
      // we want to provide a default OPTIONS handler for any path
      // so we set all the required headers and HTTP status here
      // and we give middleware functions a chance to overwrite them
      // then, in the `preBottom` function, we'll return this status
      // (or the value it was overwritten with) if no middleware
      // handles this path
      if (ctx.method === 'OPTIONS') {
        ctx.response.status = 204
        ctx.response.set('Allow', this.methods.toString())
      }
      return goToMiddleMiddleware()
    }

    function preBottom(ctx, goToBottomMiddleware) {
      // If no route match or no methods are defined, go to next middleware
      if (node.isGag || !node.methods.size) {
        return next()
      }

      // If there is no one middleware
      // it's a 405 error
      //
      // normally we'd return a 405 here since no route handles this path
      // but we provide a default OPTIONS handler
      // we've already set-up all of the necessary headers and HTTP statuses
      // so we'll just keep those
      if (!bottom.length && ctx.method !== 'OPTIONS') {
        ctx.response.set('Allow', this.methods.toString())
        ctx.response.status = 405
        return
      }

      return goToBottomMiddleware()
    }
  }
```

Here I've moved middleware's logic to the separate function `preMiddle` for better reading and understanding.

If it is OK and you don't see any pitfalls here I would merge these changes into main branch.

**Comment by alexghr** [comment]
I like the idea, it helps the readability :+1:. I'll amend the commit later today

**Comment by nervgh** [comment]
@alexghr thanks! Feel free to add one more commit to your PR :wink:

**Comment by nervgh** [comment]
I couldn’t have done it without you :ok_hand: :wink: 

p.s.:  I've published your changes as `2.1.7`

**Pull request merged**
